### PR TITLE
Adopt python bootstrap conventions

### LINKED ISSUE #190: Adopt new Python bootstrap conventions
Adopt conventions and tooling from https://github.com/openzim/_python-bootstrap/

### PR DESCRIPTION
**Pull request by benoit74**
Fix #190 

Changes:
- use hatch instead of setuptools
- fix requirements versions
- add invoke tasks
- many small adjustments to align with (new) Python / ruff conventions
- few hints (`# noqa` or `# type:ignore`) to disable some issues (ones needing a investigation / action are all tracked in a specific issue)
- support only Python 3.11 (especially dropped support for Python 2)

- - -
This change is [Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191)

### CODE REVIEW

**Review by benoit74 — COMMENTED** [review]
+reviewer:@rgaudin 

> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191#-:-Nc6mTII0uiN7M7UOtWH:bybr4xd)* status: 0 of 86 files reviewed, 18 unresolved discussions (waiting on @rgaudin)

___
*[`MANIFEST.in` line 0 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6fd0CD6ykCW3t7mei:-Nc6fd0CD6ykCW3t7mej:bwx2ycg) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/MANIFEST.in#L0)):*
What is this file used for / where is it used?
___
*[`src/gutenberg2zim/checkdeps.py` line 1 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6g8MWEKtIpC8uMwQJ:-Nc6g8MWEKtIpC8uMwQK:b-cfvsrz) ([raw file](https://github.com/openzim/gutenberg/blob/1ea3cc174e56a836a2ae7a63d0352549906304c8/src/gutenberg2zim/checkdeps.py#L1)):*
> ```Python
> #!/usr/bin/env python
> ```

Is it ok to remove these headers or do we need to maintain them? Looks like they are unused by the team now, so from my PoV it is useless to maintain them
___
*[`src/gutenberg2zim/checkdeps.py` line 33 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6gSzn9SSXGABb1UT-:-Nc6gSzn9SSXGABb1UT0:byt1xcx) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/checkdeps.py#L33)):*
> ```Python
>     all_good = True
>     has_zimwriter = True
>     for binary, msg in all_bins.items():
> ```

renamed to not shadow built-in
___
*[`src/gutenberg2zim/database.py` line 40 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6gfRo6aXQtzOf4xbs:-Nc6gfRo6aXQtzOf4xbt:b9f74lk) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/database.py#L40)):*
> ```Python
>     class Meta:
>         database = db
>         fixtures = (
> ```

tuple is not mutable while list is, and it is recommended to not have mutable class attributes (and we do not modify them anyway)
___
*[`src/gutenberg2zim/download.py` line 39 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6hJYu8JImM7DkYBX4:-Nc6hJYu8JImM7DkYBX5:bjdc6cr) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/download.py#L39)):*
> ```Python
> 
> 
> def handle_zipped_epub(zippath, book, dst_dir: pathlib.Path):
> ```

Just to help pyright understand what is going on
___
*[`src/gutenberg2zim/download.py` line 109 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6hUlm4SATFn-hl6D8:-Nc6hUlm4SATFn-hl6D9:b-6hz0cb) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/download.py#L109)):*
> ```Python
> 
> 
> def download_book(
> ```

Type hints for pyright, again
___
*[`src/gutenberg2zim/download.py` line 205 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6h_oI7hwIwUeyAhiT:-Nc6h_oI7hwIwUeyAhiU:brvko80) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/download.py#L205)):*
> ```Python
>         if bfs.count() > 1:
>             try:
>                 bf = bfs.filter(bfs.images).get()
> ```

This one was a real bug !
___
*[`src/gutenberg2zim/download.py` line 255 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6hhFX-xyJ3cxPClB-:-Nc6hhFX-xyJ3cxPClB0:best5gx) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/download.py#L255)):*
> ```Python
>                     continue
>                 # save etag
>                 book.html_etag = etag  # type: ignore
> ```

All these one are linked to peewee issue with pyright, maybe/probably solved in a more recent version
___
*[`src/gutenberg2zim/download.py` line 361 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6i5R22JgVg9o0zxRv:-Nc6i5R22JgVg9o0zxRw:bta8adg) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/download.py#L361)):*
> ```Python
> 
> def download_all_books(
>     download_cache: str,
> ```

Type hints to help pyright
___
*[`src/gutenberg2zim/entrypoint.py` line 16 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6iDEq2IoRmOtMcmcv:-Nc6iDEq2IoRmOtMcmcw:bvv793x) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/entrypoint.py#L16)):*
> ```Python
> from gutenberg2zim.zim import build_zimfile
> 
> help_info = (
> ```

do not shadow
___
*[`src/gutenberg2zim/entrypoint.py` line 73 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6iKRQ8czSZ9VV8rc9:-Nc6iKRQ8czSZ9VV8rcA:bv3bz5h) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/entrypoint.py#L73)):*
> ```Python
> 
> def main():
>     arguments = docopt(help_info, version=VERSION)
> ```

no need to pass as parameter
___
*[`src/gutenberg2zim/entrypoint.py` line 76 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6iHfT4ah0IfDaoFni:-Nc6iHfU3OSy7iQKqm1X:b68kq37) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/entrypoint.py#L76)):*
> ```Python
> 
>     # optimizer version to use
>     optimizer_version = {"html": "v1", "epub": "v1", "cover": "v1"}
> ```

all lower case
___
*[`src/gutenberg2zim/export.py` line 190 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6iykuBRwnuFsO3wGq:-Nc6iykuBRwnuFsO3wGr:bq6zwuc) ([raw file](https://github.com/openzim/gutenberg/blob/1ea3cc174e56a836a2ae7a63d0352549906304c8/src/gutenberg2zim/export.py#L190)):*
> ```Python
> def export_all_books(
>     project_id,
>     download_cache=None,
> ```

useless default values, always passed + misleading, because in many case we do not test that parameters might be None, and even assume that it is not None
___
*[`src/gutenberg2zim/export.py` line 240 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6jMRY7538v30NXXtO:-Nc6jMRZCd6bYrMGp7XS:b-pm7dte) ([raw file](https://github.com/openzim/gutenberg/blob/1ea3cc174e56a836a2ae7a63d0352549906304c8/src/gutenberg2zim/export.py#L240)):*
> ```Python
>     export_to_json_helpers(
>         books=books,
>         languages=languages,
> ```

Unused params in function, removed
___
*[`src/gutenberg2zim/export.py` line 443 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6jYSp2ifgx9YvsO6A:-Nc6jYSp2ifgx9YvsO6B:bc2dk2a) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/export.py#L443)):*
> ```Python
>                 [
>                     1
>                     for e in body.children  # type: ignore
> ```

Many BS type issues, all ignored
___
*[`src/gutenberg2zim/export.py` line 768 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6k3ATERm-UjxQaLkI:-Nc6k3ATERm-UjxQaLkJ:b-4xxydo) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/export.py#L768)):*
> ```Python
>     def handle_companion_file(
>         fname,
>         book: Book,
> ```

Reordering to express that book has no default (it must be passed) and cannot be None
___
*[`src/gutenberg2zim/shared.py` line 77 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6kkrt1tGwyC1Egm6y:-Nc6kkrt1tGwyC1Egm6z:b-if6qx3) ([raw file](https://github.com/openzim/gutenberg/blob/1ea3cc174e56a836a2ae7a63d0352549906304c8/src/gutenberg2zim/shared.py#L77)):*
> ```Python
>                 should_compress=should_compress,
>                 delete_fpath=delete_fpath,
>                 callback=callback,
> ```

Unused + typing issue, so removed for now
___
*[`src/gutenberg2zim/utils.py` line 78 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6kwOWB9Mm3J1ZwQPC:-Nc6kwOWB9Mm3J1ZwQPD:b-kpz8lq) ([raw file](https://github.com/openzim/gutenberg/blob/1ea3cc174e56a836a2ae7a63d0352549906304c8/src/gutenberg2zim/utils.py#L78)):*
> ```Python
> 
> 
> def get_project_id(languages=[], formats=[], only_books=[]):
> ```

Mutable defaults are not recommended + useless here

**Review by benoit74 — COMMENTED** [review]
Oups, I forgot to really fix requirements version. Will do it after your review, sorry.

> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191#-:-Nc6o2Iz5qM-bGyKCvHN:b-qoez2n)* status: 0 of 86 files reviewed, 18 unresolved discussions (waiting on @rgaudin)

**Review by benoit74 — COMMENTED** [review]
And I also forgot to fix Github workflows. Will do it later as well.

> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191#-:-Nc6tWSB1FedxKfxPtXc:b1f3t50)* status: 0 of 86 files reviewed, 18 unresolved discussions (waiting on @rgaudin)

**Review by rgaudin — CHANGES_REQUESTED** [review]
it seems you've not used git to move the module to src/. We're loosing all per-file history. Please revert, use `git mv` and reapply your changes

> Reviewed 84 of 86 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191#-:-Nc70sQpADRYssFaUEyU:bplmj6f)* status: all files reviewed, 31 unresolved discussions (waiting on @benoit74)

___
*[`MANIFEST.in` line  at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6fd0CD6ykCW3t7mei:-Nc6xUue55lXYr6Pk8Q0:bblcylh) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/MANIFEST.in#L)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

What is this file used for / where is it used?
</blockquote></details>

This is part of the setuptools/distutils distribution. Rendered obsolete by our new bootstrap
___
*[`pyproject.toml` line 22 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zGxYAyYuWq8lkw-F:-Nc6zGxYAyYuWq8lkw-G:b-5ec1l4) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L22)):*
> ```TOML
>     "Jinja2==3.1.2",
>     "peewee==3.15.4",
>     "path.py==12.5.0",
> ```

I saw you opened a ticket about pathlib but did not mention this. Should probably be mentioned there
___
*[`pyproject.toml` line 28 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6z_jU1_Tk1xbtdRLV:-Nc6z_jU1_Tk1xbtdRLW:b-2slyqa) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L28)):*
> ```TOML
>     "chardet==5.1.0",
>     "apsw==3.40.0.0",
>     "kiwixstorage>=0.5,<1.0",
> ```

Why the range?
___
*[`pyproject.toml` line 29 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zbQG11LEEUf7XKeI:-Nc6zbQG11LEEUf7XKeJ:b-80wp0l) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L29)):*
> ```TOML
>     "apsw==3.40.0.0",
>     "kiwixstorage>=0.5,<1.0",
>     "requests>=2.23,<3.0",
> ```

Same question
___
*[`pyproject.toml` line 31 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zd2k2rLdK_SZ69ge:-Nc6zd2k2rLdK_SZ69gf:b-1osywe) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L31)):*
> ```TOML
>     "requests>=2.23,<3.0",
>     "pif==0.8.2",
>     "zimscraperlib>=2.1,<2.2",
> ```

And again
___
*[`pyproject.toml` line 32 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zePP3yXItPIWgae-:-Nc6zePQ7-eeXTrh-a13:b44u29) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L32)):*
> ```TOML
>     "pif==0.8.2",
>     "zimscraperlib>=2.1,<2.2",
>     "schedule>=1.1.0,<1.2",
> ```

😉
___
*[`pyproject.toml` line 46 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7-cBFC-qYKXnpkQBt:-Nc7-cBFC-qYKXnpkQBu:b-g5kcv9) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L46)):*
> ```TOML
> ]
> check = [
>   "pyright==1.1.318",
> ```

Pretty sure we're at 323 ATM
___
*[`pyproject.toml` line 55 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zmVg9SRCimLtDPiS:-Nc6zmVg9SRCimLtDPiT:bv0hoxx) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L55)):*
> ```TOML
>     "pre-commit==3.3.3",
>     "debugpy==1.6.7",
> # ipdb==0.13.11
> ```

Leave them in l it's dev afterall. I tend to install both in most projects so I'd support its addition to bootstrap
___
*[`pyproject.toml` line 93 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7-UBTDH173tQImfWg:-Nc7-UBTDH173tQImfWh:b-1rmea) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L93)):*
> ```TOML
> report-cov = "inv report-cov"
> coverage = "inv coverage --args '{args}'"
> ```

No html script? Is this up to date?
___
*[`src/gutenberg2zim/__main__.py` line 7 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7BpuYBVoaKsoio7r5:-Nc7BpuYBVoaKsoio7r6:b-dr8o5e) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/__main__.py#L7)):*
> ```Python
> def main():
>     # allows running it from source using python gutenberg2zim
>     sys.path = [str(pathlib.Path(__file__).parent.parent.resolve()), *sys.path]
> ```

We should drop this hack and run it as the other projects
___
*[`src/gutenberg2zim/checkdeps.py` line 1 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6g8MWEKtIpC8uMwQJ:-Nc71QG--6GVTc5ehPFQ:b-d34lwe) ([raw file](https://github.com/openzim/gutenberg/blob/1ea3cc174e56a836a2ae7a63d0352549906304c8/src/gutenberg2zim/checkdeps.py#L1)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

Is it ok to remove these headers or do we need to maintain them? Looks like they are unused by the team now, so from my PoV it is useless to maintain them
</blockquote></details>

I agree. 
___
*[`src/gutenberg2zim/database.py` line 192 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc72JCo-jdlb2tYbFe1:-Nc72JCo-jdlb2tYbFe2:bbp0ref) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/database.py#L192)):*
> ```Python
>     downloaded_from = CharField(max_length=300, null=True)
> 
>     def __unicode__(self):
> ```

Since you're dropping py2 support, you should rename those `__unicode__` to `__str__`
___
*[`src/gutenberg2zim/download.py` line 205 at r1](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6h_oI7hwIwUeyAhiT:-Nc769r-6h4pId0QSepT:b-8fx2u7) ([raw file](https://github.com/openzim/gutenberg/blob/02d6d2f5a25ca48b1131e34b01d75e544583cdd8/src/gutenberg2zim/download.py#L205)):*
<details><summary><i>Previously, benoit74 wrote…</i></summary><blockquote>

This one was a real bug !
</blockquote></details>

:+1: 
___
*[`src/gutenberg2zim/download.py` line 81 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc72rVsA3yMHpEjx5E9:-Nc72rVsA3yMHpEjx5EA:b92wn7) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/download.py#L81)):*
> ```Python
>         src = os.path.join(tmpd, fname)
>         if os.path.exists(src):
>             fname_path = Path(fname).basename()
> ```

`fname_path` doesn't really makes sense. I understand it's used not to designate a *path* but the object type (from path.py)
___
*[`src/gutenberg2zim/entrypoint.py` line 135 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc76zDOAke1hoQCXnm5:-Nc76zDOAke1hoQCXnm6:bbwfi5o) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/entrypoint.py#L135)):*
> ```Python
> 
>     try:
>         books = list(books.split(","))
> ```

split() already returns a list
___
*[`src/gutenberg2zim/urls.py` line 233 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7B9dY2v6qa_K0_XUA:-Nc7B9dY2v6qa_K0_XUB:b84dndx) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/urls.py#L233)):*
> ```Python
> 
> def setup_urls(force):
>     file_with_url = os.path.join("tmp", f"file_on_{UrlBuilder.SERVER_NAME}")
> ```

Shouldn't this use the TMP constant?

**Review by rgaudin — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191)* status: all files reviewed, 32 unresolved discussions (waiting on @benoit74)

___
*[`.github/workflows/Publish.yaml` line 29 at r3](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7FdL9ET8T8U0RJv6o:-Nc7FdL9ET8T8U0RJv6p:b-y6tzmy) ([raw file](https://github.com/openzim/gutenberg/blob/54969c8acd688e818962b068dfcf8a94b81cdd05/.github/workflows/Publish.yaml#L29)):*
> ```YAML
>       - name: Upload to PyPI
>         uses: pypa/gh-action-pypi-publish@release/v1.8
> ```

The comments on bootstrap are important IMO. Especially since this requires manual intervention to enable Trusted Publishing for all projects (as we switch them to the bottstrap).
I just added it

**Review by benoit74 — COMMENTED** [review]
Ready for a new review

> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191#-:-Nc7P2zB3l9CNoZw1KOP:b-tuta6o)* status: all files reviewed, 19 unresolved discussions (waiting on @rgaudin)

___
*[`pyproject.toml` line 22 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zGxYAyYuWq8lkw-F:-Nc7KA661nKQYBl9hV9Y:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L22)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

I saw you opened a ticket about pathlib but did not mention this. Should probably be mentioned there
</blockquote></details>

Done.
___
*[`pyproject.toml` line 28 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6z_jU1_Tk1xbtdRLV:-Nc7KBBy6l6URykmi-1w:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L28)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Why the range?
</blockquote></details>

Done.
___
*[`pyproject.toml` line 29 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zbQG11LEEUf7XKeI:-Nc7KBx07HFfcp4DmtcX:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L29)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Same question
</blockquote></details>

Done.
___
*[`pyproject.toml` line 31 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zd2k2rLdK_SZ69ge:-Nc7KCS42v49RBXl5Ccj:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L31)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

And again
</blockquote></details>

Done.
___
*[`pyproject.toml` line 32 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zePP3yXItPIWgae-:-Nc7KGOR0wh2pdp9TlJm:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L32)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

😉
</blockquote></details>

Done.
___
*[`pyproject.toml` line 46 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7-cBFC-qYKXnpkQBt:-Nc7KwVr0nrvS-L2UZym:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L46)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Pretty sure we're at 323 ATM
</blockquote></details>

Done.
___
*[`pyproject.toml` line 55 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc6zmVg9SRCimLtDPiS:-Nc7KxHOCQAQKy-KESGI:bb6un1j) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L55)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Leave them in l it's dev afterall. I tend to install both in most projects so I'd support its addition to bootstrap
</blockquote></details>

Done
___
*[`pyproject.toml` line 93 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7-UBTDH173tQImfWg:-Nc7L24X36gidfz2xlyx:b-vo8ne3) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/pyproject.toml#L93)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

No html script? Is this up to date?
</blockquote></details>

Done
It has been added in r3 ;o)
___
*[`.github/workflows/Publish.yaml` line 29 at r3](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7FdL9ET8T8U0RJv6o:-Nc7LQGQ5l8FBPHmkX4Z:buyg380) ([raw file](https://github.com/openzim/gutenberg/blob/54969c8acd688e818962b068dfcf8a94b81cdd05/.github/workflows/Publish.yaml#L29)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

The comments on bootstrap are important IMO. Especially since this requires manual intervention to enable Trusted Publishing for all projects (as we switch them to the bottstrap).
I just added it
</blockquote></details>

What do you mean? I should keep the comments from the bootstrap here? You explicitly asked me to remove them since we were using Trusted Publishing on another project. And yes, I know that it meant that you had to perform a manual intervention. I don't mind to add the comment back.
___
*[`src/gutenberg2zim/__main__.py` line 7 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7BpuYBVoaKsoio7r5:-Nc7M4KuDAuC5-5dRm2S:be09158) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/__main__.py#L7)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

We should drop this hack and run it as the other projects
</blockquote></details>

Done
This hack seems useless indeed
___
*[`src/gutenberg2zim/database.py` line 192 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc72JCo-jdlb2tYbFe1:-Nc7MPvC7Czo8hmCnMbn:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/database.py#L192)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Since you're dropping py2 support, you should rename those `__unicode__` to `__str__`
</blockquote></details>

Done.
___
*[`src/gutenberg2zim/download.py` line 81 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc72rVsA3yMHpEjx5E9:-Nc7Mebb5_crWQWQyot9:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/download.py#L81)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

`fname_path` doesn't really makes sense. I understand it's used not to designate a *path* but the object type (from path.py)
</blockquote></details>

Done.
___
*[`src/gutenberg2zim/urls.py` line 233 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7B9dY2v6qa_K0_XUA:-Nc7P136CqQWO15y73W3:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/urls.py#L233)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Shouldn't this use the TMP constant?
</blockquote></details>

Done.

**Review by benoit74 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191)* status: 85 of 92 files reviewed, 19 unresolved discussions (waiting on @rgaudin)

___
*[`src/gutenberg2zim/entrypoint.py` line 135 at r2](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc76zDOAke1hoQCXnm5:-Nc7PZQB8j0ZPUagK-3E:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/6ef204283d4888704cee0d160b476ed06a676b27/src/gutenberg2zim/entrypoint.py#L135)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

split() already returns a list
</blockquote></details>

Done.

**Review by rgaudin — CHANGES_REQUESTED** [review]
Good ; there's the workflow thing and then I think it's OK but you'll have to fix the git history

> Reviewed 9 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191#-:-Nc7Xqq47blEZdc6nSiA:ba3052n)* status: 92 of 94 files reviewed, 7 unresolved discussions (waiting on @benoit74)

___
*[`.pre-commit-config.yaml` line 18 at r4](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7X4bT3bevGSK84nPE:-Nc7X4bT3bevGSK84nPF:bstbhl3) ([raw file](https://github.com/openzim/gutenberg/blob/45e5604a597b002fe77a8e26e37ca960fbc90376/.pre-commit-config.yaml#L18)):*
> ```YAML
>   - id: ruff
> - repo: https://github.com/RobertCraigie/pyright-python
>   rev: v1.1.315
> ```

Is this in line with pyproject?

**Review by rgaudin — COMMENTED** [review]
> Reviewed 2 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191)* status: all files reviewed, 7 unresolved discussions (waiting on @benoit74)

**Review by benoit74 — COMMENTED** [review]
What do you want to fix in the git history? 

I used `git mv`, but indeed I realized that it makes no difference : https://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history

But I agree that I could squash most commits 

What is the workflow thing?

> *[Reviewable](https://reviewable.io/reviews/openzim/gutenberg/191#-:-Nc7hFmBAZrTl8GObcce:b-pjswz6)* status: all files reviewed, 7 unresolved discussions (waiting on @benoit74 and @rgaudin)

___
*[`.pre-commit-config.yaml` line 18 at r4](https://reviewable.io/reviews/openzim/gutenberg/191#-Nc7X4bT3bevGSK84nPE:-Nc7h8p48HL_cFhL9P6W:b-896fix) ([raw file](https://github.com/openzim/gutenberg/blob/45e5604a597b002fe77a8e26e37ca960fbc90376/.pre-commit-config.yaml#L18)):*
<details><summary><i>Previously, rgaudin (rgaudin) wrote…</i></summary><blockquote>

Is this in line with pyproject?
</blockquote></details>

Done.

**Pull request merged**
