### PR TITLE
Adds german translations.

### PR DESCRIPTION
**Pull request by AVGP**
refs #56

### CODE REVIEW

**Comment by kelson42** [comment]
@AVGP Thx for the PR!

**Comment by dattaz** [comment]
Hello,
Thanks a lot for you PR !
Can you add initialization for german please ? (see https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/templates/l10n/locales.ini)

**Comment by AVGP** [comment]
@dattaz done :shipit:

**Comment by dattaz** [comment]
Thanks :+1: :fireworks:

**Comment by dattaz** [comment]
@AVGP Hi, we found with your PR that we have 2 system for translations, I am unifying them, but i'm missing some german strings, can you give me them by comment here ? Thanks.

"Interface language" :  (https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py#L26)
 "List books of a single Author" : ( https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py#L33 )
 "Choose the Catalog" : ( https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py#L79 )
"Main languages" : ( https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py#L82 )
 "Other languages" : ( https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py#L85 )

**Comment by kelson42** [comment]
@dattaz done https://github.com/openzim/gutenberg/commit/c663232e372942839b8849e38744c88c4a6c6b5f

**Pull request merged**
