### PR TITLE
Now JS will be added during setup

### PR DESCRIPTION
**Pull request by hksingh4545**
Now JS of DataTables-1.10.13 and Responsive-2.1.1 will be added during setup

### CODE REVIEW

**Comment by kelson42** [comment]
@hksingh4545 Thx

**Review by rgaudin — CHANGES_REQUESTED** [review]
Thanks. I see the files are not identical. Diff tells me for example that the new file refers to 

```css
.sorting{background-image:url("/DataTables-1.10.13/images/sort_both.png")
```

Kinda the same for all images.

Now I see that we did not have those images in the repo. I can't say if we are not using the features using them or if it's broken but this is a good opportunity to fix it. If that's not a nightmare to fix ; as it might be difficult to find this old archive (my understanding is that it's a bundle).

Also we should only keep one version (minified?) of CSS and JS.

**Comment by kelson42** [comment]
@hksingh4545 Any feedback?

**Comment by kelson42** [comment]
@hksingh4545 Without feedback, I will have to close this ticket unfortunately :( Would you be able please to answer @rgaudin' comment?

**Comment by hksingh4545** [comment]
can you explain a little more about it?

**Comment by rgaudin** [comment]
> can you explain a little more about it?

I don't understand. Is there something specific about my previous comment that is not clear?

**Comment by hksingh4545** [comment]
Is the file which is including during setup is different from current one?

**Comment by kelson42** [comment]
@rgaudin any feedback?

**Pull request closed without merging**
