### PR TITLE
Fixed bookshelves related bugs

### LINKED ISSUE #105: Books which contains a slash in title are unreachable via title
The new bookshelf-related title search allows to jump into a book directly by searching for its title.

Unfortunately this feature is not using the title rewriting and thus tries to access the cover file with a `/` while it had been rewritten to a `-` in the FS and thus in the zim.

### LINKED ISSUE #106: remove bookshelves link if not using `--bookshelves`
The *Browse by bookshelves* link is present on home page even if the `--bookshelves` has not been set, resulting in a broken link.

### LINKED ISSUE #107: fix --title-search help string
Needs to explain what it does.

### LINKED ISSUE #108: restore commented-out setup_urls()
`setup_urls()` is a long yet required step in `DO_PARSE` that has been commented out, probably for development.

It must be restored.

### PR DESCRIPTION
**Pull request by satyamtg**
This PR does the following -
- Fixes #106  - Correct the showing and hiding of the "Go to bookshelves" link
- Fixes #107 
- Fixes #105
- Fixes #108 

To make it easier to review - 
- Changes related to fixing #106 are in `gutenbergtozim/templates/base.html` and in lines 982, 999 in `gutenbergtozim/export.py`

### CODE REVIEW

**Comment by rgaudin** [comment]
Don't mix formatting and bug-fix otherwise this PR will have to be reviewed commit-by-commit !!!

Send a formatting-only PR first that we'll merge so that this becomes bug-fix only.

**Comment by satyamtg** [comment]
> Don't mix formatting and bug-fix otherwise this PR will have to be reviewed commit-by-commit !!!
> 
> Send a formatting-only PR first that we'll merge so that this becomes bug-fix only.

Created #111 which only adds black formatting to python files

**Comment by rgaudin** [comment]
Another thing I just discovered ; could you please integrate this as well (so that we don't have static English strings there):

``` diff
diff --git i/gutenbergtozim/templates/bookshelf.html w/gutenbergtozim/templates/bookshelf.html
index 593fd73..ac3298c 100644
--- i/gutenbergtozim/templates/bookshelf.html
+++ w/gutenbergtozim/templates/bookshelf.html
@@ -1,7 +1,7 @@
 {% extends "base.html" %}
-{% block title %}Individual Bookshelf{% endblock %}
+{% block title %}{{ bookshelf }}{% endblock %}
 {% block content %}
-<h1 class="table-title">{{ bookshelf }} Bookshelf</h1>
+<h1 class="table-title">{{ bookshelf }}</h1>
 <table class="data-table display" cellpadding="0" cellspacing="0" border="0" id="books_table"></table>
 <script type="text/javascript">
```

**Comment by rgaudin** [comment]
There's no review requested but I checked the rest and it's OK. We'll merge once you fix those strings in the template.

**Pull request merged**
