### PR TITLE
Remove unused variables from tool.js

### LINKED ISSUE #158: Resolve CodeFactor issues on tools.js
CodeFactor is currently complaining about many issues in `templates/js/tools.js`

Most of them should be fixed. Usually the only one which are tolerated are the "complex method" ones (which would need a massive revamping).

See e.g. https://github.com/openzim/gutenberg/pull/157/checks?check_run_id=10676559369

### PR DESCRIPTION
**Pull request by theparthshukla**
fix #158 Removed unused variables, however left unused functions intact.

### CODE REVIEW

**Comment by benoit74** [comment]
LGTM from my mobile, I will run a more detailed review (including a test with a real ZIM) later to confirm this.

@rgaudin @kelson42 @theparthshukla : do you have experience of situations where old browsers would complain that JavaScript function are missing an argument?

Here an additional argument is passed by the caller but not used in the function, so we can remove it, but is it a recent convention or something which has almost always been supported in JavaScript ?

I'm a bit afraid of testing these JavaScript on recent modern browsers while we know that a significant portion of Kiwix/ZIM users are still on very old versions

**Comment by kelson42** [comment]
This is more a question for our JS expert @Jaifroid

**Comment by Jaifroid** [comment]
@benoit74 Gutenberg ZIMs can be read on old browsers so long as the user uses the native search to access book covers and the books themselves, and not the proprietary UI (which doesn't work in Kiwix JS versions if the browser doesn't support Service Workers, because only in Service Worker mode can the app run JS in the ZIM).

There is, however, a specific issue #145 with Chromium extensions (Chrome, Edge, etc.). These ban the use of inline JS, which means that the proprietary UI also doesn't work in the latest Chromium browsers **in the extension/add-on version**. The UI **does** work in the PWA version (pwa.kiwix.org).

Generally it's pretty trivial to change the use of inline JS by putting inline scripts into a separate .js files and simply loading them in the HTML.

**Comment by kelson42** [comment]
What is the status here?

**Comment by benoit74** [comment]
Never had time to review this in more details, and it looks like it will
not happen in the short term :-(

**Comment by rgaudin** [comment]
Wouldn't fix the issue as there are additional unused variables in the file. Hint, codefactor listed 28, only 22 are fixed here. Please complete.

**Review by rgaudin — CHANGES_REQUESTED** [review]
Wouldn't fix the issue as there are additional unused variables in the file. Hint, codefactor listed 28, only 22 are fixed here. Please complete.

**Comment by kelson42** [comment]
@theparthshukla Any news?

**Comment by theparthshukla** [comment]
@kelson42 whoops, the notification seems to have missed my mailbox. Will get to this later today

**Comment by theparthshukla** [comment]
Line #65 ‘goToAuthor’ is defined but not used. However, it is actually used in “cover_article.html” on line #20. 

Line #392 'showBookshelf' is defined but never used. However, it is actually used in “base.html” on line #29.

Line #611 ‘init’ is defined but never used. However, it is actually used in “base.html” on line #29.

These were 3 issues of the 28 that were not taken care of as they were incorrectly identified.

Upon removal of the function “queryParams” as it was a function made redundant by the removal of the function “getRequestedPage”, (not identified in the initial issues) we get a total of 26 issues fixed.

**Review by rgaudin — APPROVED** [review]
Thank you! Works fine 👍

**Pull request merged**
